---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: aodh_install_apt.yml
  when:
    - ansible_pkg_mgr == 'apt'
  tags:
    - install-apt

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in aodh_developer_constraints %}
      {{ item }}
      {% endfor %}
  when:
    - aodh_developer_mode | bool
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Clone requirements git repository
  git:
    repo: "{{ aodh_requirements_git_repo }}"
    dest: "/opt/requirements"
    clone: yes
    update: yes
    version: "{{ aodh_requirements_git_install_branch }}"
  when:
    - aodh_developer_mode | bool
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Add constraints to pip_install_options fact for developer mode
  set_fact:
    pip_install_options_fact: "{{ pip_install_options|default('') }} --constraint /opt/developer-pip-constraints.txt --constraint /opt/requirements/upper-constraints.txt"
  when:
    - aodh_developer_mode | bool
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Set pip_install_options_fact when not in developer mode
  set_fact:
    pip_install_options_fact: "{{ pip_install_options|default('') }}"
  when:
    - not aodh_developer_mode | bool
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Install requires pip packages
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: "{{ pip_install_options_fact }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ aodh_requires_pip_packages }}"
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Get local venv checksum
  stat:
    path: "/var/cache/{{ aodh_venv_download_url | basename }}"
    get_md5: False
  when:
    - not aodh_developer_mode | bool
  register: local_venv_stat
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Get remote venv checksum
  uri:
    url: "{{ aodh_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: True
  when:
    - not aodh_developer_mode | bool
  register: remote_venv_checksum
  tags:
    - aodh-install
    - aodh-pip-packages

# TODO: When project moves to ansible 2 we can pass this a sha256sum which will:
#       a) allow us to remove force: yes
#       b) allow the module to calculate the checksum of dest file which would
#          result in file being downloaded only if provided and dest sha256sum
#          checksums differ
- name: Attempt venv download
  get_url:
    url: "{{ aodh_venv_download_url }}"
    dest: "/var/cache/{{ aodh_venv_download_url | basename }}"
    force: yes
  ignore_errors: true
  register: get_venv
  when:
    - not aodh_developer_mode | bool
    - (local_venv_stat.stat.exists == False or
        {{ local_venv_stat.stat.checksum is defined and local_venv_stat.stat.checksum != remote_venv_checksum.content | trim }})
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Set aodh get_venv fact
  set_fact:
    aodh_get_venv: "{{ get_venv }}"
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Remove existing venv
  file:
    path: "{{ aodh_bin | dirname }}"
    state: absent
  when:
    - aodh_get_venv | changed
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Create aodh venv dir
  file:
    path: "{{ aodh_bin | dirname }}"
    state: directory
  register: aodh_venv_dir
  when:
    - not aodh_developer_mode | bool
    - aodh_get_venv | changed
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ aodh_venv_download_url | basename }}"
    dest: "{{ aodh_bin | dirname }}"
    copy: "no"
  when:
    - not aodh_developer_mode | bool
    - aodh_get_venv | changed or aodh_venv_dir | changed
  notify: Restart aodh services
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ aodh_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: "{{ pip_install_options_fact }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ aodh_pip_packages }}"
  when:
    - aodh_get_venv | failed or aodh_developer_mode | bool
  notify: Restart aodh services
  tags:
    - aodh-install
    - aodh-pip-packages

- name: Update virtualenv path
  command: >
    virtualenv-tools --update-path=auto {{ aodh_bin | dirname }}
  when:
    - not aodh_developer_mode | bool
  tags:
    - aodh-install
    - aodh-pip-packages